global:
  namespace: votingapp

replicaCount: 1

# Redis helm settings
redis:
  image: 
    repository: redis
    tag: latest
  imagePullPolicy: Always
  
# Postgres helm settings
db:
  image: 
    repository: postgres
    tag: 15-alpine
  imagePullPolicy: Always

worker:
  image: 
    repository: 292526779943.dkr.ecr.eu-central-1.amazonaws.com/app/worker
    tag: 83c39691
  imagePullPolicy: Always

vote:
  image: 
    repository: 292526779943.dkr.ecr.eu-central-1.amazonaws.com/app/vote-app
    tag: 83c39691
  imagePullPolicy: Always

result:
  image: 
    repository: 292526779943.dkr.ecr.eu-central-1.amazonaws.com/app/result-app
    tag: 83c39691
  imagePullPolicy: Always
  
  
  service:
    labels:
      name: result-app-service
    ports:
    - port:  80
      targetPort:  80

appingress:
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels: 
    name: voting-appingress
  rules:
  - host: result.app.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: result
              port:
                number: 80
  - host: vote.app.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: vote
              port:
                number: 80