apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: "{{ .Values.result.image.repository}}:{{ .Values.result.image.tag }}"
        name: result
        ports:
        - containerPort: 80
          name: result
