apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: "{{ .Values.vote.image.repository}}:{{ .Values.vote.image.tag }}"
        name: vote
        ports:
        - containerPort: 80
          name: vote
